### ISSUE TITLE
Update the indexing procedures for the ArchivesSpace EADs

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#278]
There should be parity between the indexing procedure for the ArchivesSpace EADs and subversion EADs. Further, we should ensure that the fixtures for the SVN EADs are replaced with those exported from ArchivesSpace.

**Comment by jrgriffiniii** [comment]
As indicated by @tpendragon, the SVN repository for the sample EADs from ArchivesSpace can be found in https://github.com/pulibrary/pulfalight/commit/1eb83e91a85a9654cfd26497cf330d1898d7ebe7

**Comment by jrgriffiniii** [comment]
After indexing ArchivesSpace EADs, components should be visible within PULFALight. Does this require that we revert the nested indexing logic?

**Comment by jrgriffiniii** [comment]
It should be clarified here that SVN is being used here as an intermediary step to track the new ArchivesSpace-generated EADs, as they may still need to be also pushed into PULFA 2.0.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pulfalight/compare/issues-274-jrgriffiniii-traject-restore gets this passing for the updated `C0614` fixture.

**Comment by jrgriffiniii** [comment]
While progressing through the replacement of the fixtures on the branch https://github.com/pulibrary/pulfalight/compare/issues-274-jrgriffiniii-traject-restore, it was proposed that it will be more efficient to address each replaced (or added) ArchivesSpace fixture as an itemized task list:

- [x] MC221_pruned.EAD.xml
- [x] WC064_pruned.EAD.xml
- [x] C0614.EAD.xml
- [x] C0776.EAD.xml

**Comment by jrgriffiniii** [comment]
I've marked the remaining, failing tests as pending and shifted to the following branch: https://github.com/pulibrary/pulfalight/tree/issues-274-traject-aspace-update

**Comment by jrgriffiniii** [comment]
As the fixtures have been replaced, the following Traject indexing feature tests (which are marked as pending) should be advanced to become passing (with the new fixtures):

- [ ] https://github.com/pulibrary/pulfalight/compare/issues-274-traject-aspace-update#diff-664936f7cc46c51b3d3ba29e17878d14R76
- [ ] https://github.com/pulibrary/pulfalight/compare/issues-274-traject-aspace-update#diff-664936f7cc46c51b3d3ba29e17878d14R86
- [ ] https://github.com/pulibrary/pulfalight/compare/issues-274-traject-aspace-update#diff-664936f7cc46c51b3d3ba29e17878d14R140
- [ ] https://github.com/pulibrary/pulfalight/compare/issues-274-traject-aspace-update#diff-664936f7cc46c51b3d3ba29e17878d14R172
- [ ] https://github.com/pulibrary/pulfalight/compare/issues-274-traject-aspace-update#diff-664936f7cc46c51b3d3ba29e17878d14R179
- [ ] https://github.com/pulibrary/pulfalight/compare/issues-274-traject-aspace-update#diff-664936f7cc46c51b3d3ba29e17878d14R192
- [ ] https://github.com/pulibrary/pulfalight/compare/issues-274-traject-aspace-update#diff-664936f7cc46c51b3d3ba29e17878d14R199
